name: nhs-service-finder
region: lon
services:
  - name: api
    github:
      repo: AceCentre/nhs-service-finder
      branch: master
      deploy_on_push: true
    build_command: npm install
    run_command: node index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 4001
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4001"

