backend:
  name: github
  repo: acecentre/nhs-service-finder
  branch: master 

media_folder: "static/images/uploads"
media_library:
  name: uploads    
  
collections:
  - name: "nhs-service" 
    label: "Service" 
    folder: "content/ccg" 
    create: false 
    slug: "{{fields.serviceid}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Service ID", name: "serviceid", widget: "string"}
      - {label: "Service Name", name: "servicename", widget: "string"}
      - {label: "Contact Phone #", name: "contactphone", widget: "string"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Address", name: "address", widget: "text"}
      - {label: "Services offered", name: "ccgservices", widget: "select", options: ["aac", "ec", "wcs"], multiple: true}
      - {label: "CCG Codes covered", name: "ccgcodes", widget: "select", options:
            [{ label: "E38000001", value: "NHS Airedale, Wharfedale and Craven CCG" }, 
            { label: "E38000002", value: "NHS Ashford CCG" }, 
            { label: "E38000004", value: "NHS Barking and Dagenham CCG" }, 
            { label: "E38000005", value: "NHS Barnet CCG" }, 
            { label: "E38000006", value: "NHS Barnsley CCG" }, 
            { label: "E38000007", value: "NHS Basildon and Brentwood CCG" }, 
            { label: "E38000008", value: "NHS Bassetlaw CCG" }, 
            { label: "E38000009", value: "NHS Bath and North East Somerset CCG" }, 
            { label: "E38000010", value: "NHS Bedfordshire CCG" }, 
            { label: "E38000011", value: "NHS Bexley CCG" }, 
            { label: "E38000014", value: "NHS Blackburn with Darwen CCG" }, 
            { label: "E38000015", value: "NHS Blackpool CCG" }, 
            { label: "E38000016", value: "NHS Bolton CCG" }, 
            { label: "E38000018", value: "NHS Bradford City CCG" }, 
            { label: "E38000019", value: "NHS Bradford Districts CCG" }, 
            { label: "E38000020", value: "NHS Brent CCG" }, 
            { label: "E38000021", value: "NHS Brighton and Hove CCG" }, 
            { label: "E38000023", value: "NHS Bromley CCG" }, 
            { label: "E38000024", value: "NHS Bury CCG" }, 
            { label: "E38000025", value: "NHS Calderdale CCG" }, 
            { label: "E38000026", value: "NHS Cambridgeshire and Peterborough CCG" }, 
            { label: "E38000027", value: "NHS Camden CCG" }, 
            { label: "E38000028", value: "NHS Cannock Chase CCG" }, 
            { label: "E38000029", value: "NHS Canterbury and Coastal CCG" }, 
            { label: "E38000030", value: "NHS Castle Point and Rochford CCG" }, 
            { label: "E38000031", value: "NHS Central London (Westminster) CCG" }, 
            { label: "E38000034", value: "NHS Chorley and South Ribble CCG" }, 
            { label: "E38000035", value: "NHS City and Hackney CCG" }, 
            { label: "E38000037", value: "NHS Corby CCG" }, 
            { label: "E38000038", value: "NHS Coventry and Rugby CCG" }, 
            { label: "E38000039", value: "NHS Crawley CCG" }, 
            { label: "E38000040", value: "NHS Croydon CCG" }, 
            { label: "E38000042", value: "NHS Darlington CCG" }, 
            { label: "E38000043", value: "NHS Dartford, Gravesham and Swanley CCG" }, 
            { label: "E38000044", value: "NHS Doncaster CCG" }, 
            { label: "E38000045", value: "NHS Dorset CCG" }, 
            { label: "E38000046", value: "NHS Dudley CCG" }, 
            { label: "E38000047", value: "NHS Durham Dales, Easington and Sedgefield CCG" }, 
            { label: "E38000048", value: "NHS Ealing CCG" }, 
            { label: "E38000049", value: "NHS East and North Hertfordshire CCG" }, 
            { label: "E38000050", value: "NHS East Lancashire CCG" }, 
            { label: "E38000051", value: "NHS East Leicestershire and Rutland CCG" }, 
            { label: "E38000052", value: "NHS East Riding of Yorkshire CCG" }, 
            { label: "E38000053", value: "NHS East Staffordshire CCG" }, 
            { label: "E38000054", value: "NHS East Surrey CCG" }, 
            { label: "E38000055", value: "NHS Eastbourne, Hailsham and Seaford CCG" }, 
            { label: "E38000056", value: "NHS Eastern Cheshire CCG" }, 
            { label: "E38000057", value: "NHS Enfield CCG" }, 
            { label: "E38000059", value: "NHS Fareham and Gosport CCG" }, 
            { label: "E38000062", value: "NHS Gloucestershire CCG" }, 
            { label: "E38000063", value: "NHS Great Yarmouth and Waveney CCG" }, 
            { label: "E38000064", value: "NHS Greater Huddersfield CCG" }, 
            { label: "E38000066", value: "NHS Greenwich CCG" }, 
            { label: "E38000068", value: "NHS Halton CCG" }, 
            { label: "E38000069", value: "NHS Hambleton, Richmondshire and Whitby CCG" }, 
            { label: "E38000070", value: "NHS Hammersmith and Fulham CCG" }, 
            { label: "E38000072", value: "NHS Haringey CCG" }, 
            { label: "E38000073", value: "NHS Harrogate and Rural District CCG" }, 
            { label: "E38000074", value: "NHS Harrow CCG" }, 
            { label: "E38000075", value: "NHS Hartlepool and Stockton-on-Tees CCG" }, 
            { label: "E38000076", value: "NHS Hastings and Rother CCG" }, 
            { label: "E38000077", value: "NHS Havering CCG" }, 
            { label: "E38000078", value: "NHS Herefordshire CCG" }, 
            { label: "E38000079", value: "NHS Herts Valleys CCG" }, 
            { label: "E38000164", value: "NHS South Warwickshire CCG" }, 
            { label: "E38000165", value: "NHS South West Lincolnshire CCG" }, 
            { label: "E38000166", value: "NHS South Worcestershire CCG" }, 
            { label: "E38000167", value: "NHS Southampton CCG" }, 
            { label: "E38000168", value: "NHS Southend CCG" }, 
            { label: "E38000170", value: "NHS Southport and Formby CCG" }, 
            { label: "E38000171", value: "NHS Southwark CCG" }, 
            { label: "E38000172", value: "NHS St Helens CCG" }, 
            { label: "E38000173", value: "NHS Stafford and Surrounds CCG" }, 
            { label: "E38000174", value: "NHS Stockport CCG" }, 
            { label: "E38000175", value: "NHS Stoke on Trent CCG" }, 
            { label: "E38000176", value: "NHS Sunderland CCG" }, 
            { label: "E38000177", value: "NHS Surrey Downs CCG" }, 
            { label: "E38000178", value: "NHS Surrey Heath CCG" }, 
            { label: "E38000179", value: "NHS Sutton CCG" }, 
            { label: "E38000180", value: "NHS Swale CCG" }, 
            { label: "E38000181", value: "NHS Swindon CCG" }, 
            { label: "E38000182", value: "NHS Tameside and Glossop CCG" }, 
            { label: "E38000183", value: "NHS Telford and Wrekin CCG" }, 
            { label: "E38000184", value: "NHS Thanet CCG" }, 
            { label: "E38000185", value: "NHS Thurrock CCG" }, 
            { label: "E38000186", value: "NHS Tower Hamlets CCG" }, 
            { label: "E38000187", value: "NHS Trafford CCG" }, 
            { label: "E38000188", value: "NHS Vale of York CCG" }, 
            { label: "E38000189", value: "NHS Vale Royal CCG" }, 
            { label: "E38000190", value: "NHS Wakefield CCG" }, 
            { label: "E38000191", value: "NHS Walsall CCG" }, 
            { label: "E38000192", value: "NHS Waltham Forest CCG" }, 
            { label: "E38000193", value: "NHS Wandsworth CCG" }, 
            { label: "E38000194", value: "NHS Warrington CCG" }, 
            { label: "E38000195", value: "NHS Warwickshire North CCG" }, 
            { label: "E38000196", value: "NHS West Cheshire CCG" }, 
            { label: "E38000197", value: "NHS West Essex CCG" }, 
            { label: "E38000198", value: "NHS West Hampshire CCG" }, 
            { label: "E38000199", value: "NHS West Kent CCG" }, 
            { label: "E38000200", value: "NHS West Lancashire CCG" }, 
            { label: "E38000201", value: "NHS West Leicestershire CCG" }, 
            { label: "E38000202", value: "NHS West London CCG" }, 
            { label: "E38000203", value: "NHS West Norfolk CCG" }, 
            { label: "E38000204", value: "NHS West Suffolk CCG" }, 
            { label: "E38000205", value: "NHS Wigan Borough CCG" }, 
            { label: "E38000206", value: "NHS Wiltshire CCG" }, 
            { label: "E38000208", value: "NHS Wirral CCG" }, 
            { label: "E38000210", value: "NHS Wolverhampton CCG" }, 
            { label: "E38000211", value: "NHS Wyre Forest CCG" }, 
            { label: "E38000212", value: "NHS Newcastle Gateshead CCG" }, 
            { label: "E38000213", value: "NHS Coastal West Sussex CCG" }, 
            { label: "E38000214", value: "NHS Guildford and Waverley CCG" }, 
            { label: "E38000215", value: "NHS North Cumbria CCG" }, 
            { label: "E38000217", value: "NHS Manchester CCG" }, 
            { label: "E38000218", value: "NHS Norwich CCG" }, 
            { label: "E38000219", value: "NHS South Norfolk CCG" }, 
            { label: "E38000220", value: "NHS Birmingham and Solihull CCG" }, 
            { label: "E38000221", value: "NHS Berkshire West CCG" }, 
            { label: "E38000222", value: "NHS Bristol, North Somerset and South Gloucestershire CCG" }, 
            { label: "E38000223", value: "NHS Buckinghamshire CCG" }, 
            { label: "E38000224", value: "NHS East Berkshire CCG" }, 
            { label: "E38000225", value: "NHS Leeds CCG" }, 
            { label: "E38000226", value: "NHS Fylde and Wyre CCG" }, 
            { label: "E38000227", value: "NHS Greater Preston CCG" }, 
            { label: "E38000228", value: "NHS Morecambe Bay CCG" }, 
            { label: "E38000229", value: "NHS Derby and Derbyshire CCG" }, 
            { label: "E38000230", value: "NHS Devon CCG" }, 
            { label: "E38000080", value: "NHS Heywood, Middleton and Rochdale CCG" }, 
            { label: "E38000081", value: "NHS High Weald Lewes Havens CCG" }, 
            { label: "E38000082", value: "NHS Hillingdon CCG" }, 
            { label: "E38000083", value: "NHS Horsham and Mid Sussex CCG" }, 
            { label: "E38000084", value: "NHS Hounslow CCG" }, 
            { label: "E38000085", value: "NHS Hull CCG" }, 
            { label: "E38000086", value: "NHS Ipswich and East Suffolk CCG" }, 
            { label: "E38000087", value: "NHS Isle of Wight CCG" }, 
            { label: "E38000088", value: "NHS Islington CCG" }, 
            { label: "E38000089", value: "NHS Kernow CCG" }, 
            { label: "E38000090", value: "NHS Kingston CCG" }, 
            { label: "E38000091", value: "NHS Knowsley CCG" }, 
            { label: "E38000092", value: "NHS Lambeth CCG" }, 
            { label: "E38000097", value: "NHS Leicester City CCG" }, 
            { label: "E38000098", value: "NHS Lewisham CCG" }, 
            { label: "E38000099", value: "NHS Lincolnshire East CCG" }, 
            { label: "E38000100", value: "NHS Lincolnshire West CCG" }, 
            { label: "E38000101", value: "NHS Liverpool CCG" }, 
            { label: "E38000102", value: "NHS Luton CCG" }, 
            { label: "E38000103", value: "NHS Mansfield and Ashfield CCG" }, 
            { label: "E38000104", value: "NHS Medway CCG" }, 
            { label: "E38000105", value: "NHS Merton CCG" }, 
            { label: "E38000106", value: "NHS Mid Essex CCG" }, 
            { label: "E38000107", value: "NHS Milton Keynes CCG" }, 
            { label: "E38000108", value: "NHS Nene CCG" }, 
            { label: "E38000109", value: "NHS Newark and Sherwood CCG" }, 
            { label: "E38000113", value: "NHS Newham CCG" }, 
            { label: "E38000116", value: "NHS North Durham CCG" }, 
            { label: "E38000117", value: "NHS North East Essex CCG" }, 
            { label: "E38000118", value: "NHS North East Hampshire and Farnham CCG" }, 
            { label: "E38000119", value: "NHS North East Lincolnshire CCG" }, 
            { label: "E38000120", value: "NHS North Hampshire CCG" }, 
            { label: "E38000121", value: "NHS North Kirklees CCG" }, 
            { label: "E38000122", value: "NHS North Lincolnshire CCG" }, 
            { label: "E38000124", value: "NHS North Norfolk CCG" }, 
            { label: "E38000126", value: "NHS North Staffordshire CCG" }, 
            { label: "E38000127", value: "NHS North Tyneside CCG" }, 
            { label: "E38000128", value: "NHS North West Surrey CCG" }, 
            { label: "E38000130", value: "NHS Northumberland CCG" }, 
            { label: "E38000132", value: "NHS Nottingham City CCG" }, 
            { label: "E38000133", value: "NHS Nottingham North and East CCG" }, 
            { label: "E38000134", value: "NHS Nottingham West CCG" }, 
            { label: "E38000135", value: "NHS Oldham CCG" }, 
            { label: "E38000136", value: "NHS Oxfordshire CCG" }, 
            { label: "E38000137", value: "NHS Portsmouth CCG" }, 
            { label: "E38000138", value: "NHS Redbridge CCG" }, 
            { label: "E38000139", value: "NHS Redditch and Bromsgrove CCG" }, 
            { label: "E38000140", value: "NHS Richmond CCG" }, 
            { label: "E38000141", value: "NHS Rotherham CCG" }, 
            { label: "E38000142", value: "NHS Rushcliffe CCG" }, 
            { label: "E38000143", value: "NHS Salford CCG" }, 
            { label: "E38000144", value: "NHS Sandwell and West Birmingham CCG" }, 
            { label: "E38000145", value: "NHS Scarborough and Ryedale CCG" }, 
            { label: "E38000146", value: "NHS Sheffield CCG" }, 
            { label: "E38000147", value: "NHS Shropshire CCG" }, 
            { label: "E38000150", value: "NHS Somerset CCG" }, 
            { label: "E38000151", value: "NHS South Cheshire CCG" }, 
            { label: "E38000153", value: "NHS South East Staffordshire and Seisdon Peninsula CCG" }, 
            { label: "E38000154", value: "NHS South Eastern Hampshire CCG" }, 
            { label: "E38000156", value: "NHS South Kent Coast CCG" }, 
            { label: "E38000157", value: "NHS South Lincolnshire CCG" }, 
            { label: "E38000161", value: "NHS South Sefton CCG" }, 
            { label: "E38000162", value: "NHS South Tees CCG" }, 
            { label: "E38000163", value: "NHS South Tyneside CCG" }]
        }
      - {label: "Body", name: "body", widget: "markdown"}