[[headers]]
    for = "/*"

[headers.values]
    Access-Control-Allow-Origin = "*"

[build]
    functions = "functions"

[[redirects]]
    from = "/graphql"
    to = "https://servicefinder.acecentre.net/.netlify/functions/graphql"
    status = 200

[[redirects]]
    from = "/*"
    to = "https://acecentre.org.uk/nhs-service-finder"
    status = 301
    force = true