name: Update Services
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  UpdateServices:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        id: makeRequest
        with:
          url: "https://assistivetechnology.org.uk/wp-json/at-services-list/update-services"
          method: "GET"
          timeout: 10000
